---
functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Пользователь должен имень возможность добавить товар в корзину и просмотреть содержимое корзины
  - Пользователь может удалить товар из карзины
  - Пользователь на странице корзины может оформить заказ с переходом на страницу оплаты
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру.
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Данные корзины хроняться в системе браузера
  - У сайта два языка интерфейса — русский и английский
  - Корзина с товарами сохраняется даже после того, как пользователь покинул страницу
  - Переход по страницам выполняется без перезагрузки страницы #git commit #git push
  
